KANJI_DATA = {
    "0602": {
        "label": "6월 2일",
        "pages": "67, 68",
        "words": [
            {"yomigana": "ぐん", "tango": "郡", "kor": "군"},
            {"yomigana": "けいたい", "tango": "携帯", "kor": "휴대"},
            {"yomigana": "おび", "tango": "帯び", "kor": "매듭"},
            {"yomigana": "せいと", "tango": "生徒", "kor": "생도/학생"},
            {"yomigana": "れんけつ", "tango": "連結", "kor": "연결"},
            {"yomigana": "れんぞく", "tango": "連続", "kor": "연속"},
            {"yomigana": "つれる", "tango": "連れる", "kor": "데리고오다"},
            {"yomigana": "りょうきん", "tango": "料金", "kor": "요금"},
            {"yomigana": "りょうり", "tango": "料理", "kor": "요리"},
            {"yomigana": "ばいか", "tango": "梅花", "kor": "매화"},
            {"yomigana": "うめしゅ", "tango": "梅酒", "kor": "매실주"},
            {"yomigana": "じんみゃく", "tango": "人脈", "kor": "인맥"},
            {"yomigana": "どうみゃく", "tango": "動脈", "kor": "동맥"},
            {"yomigana": "じょうみゃく", "tango": "静脈", "kor": "정맥"},
            {"yomigana": "ふんまつ", "tango": "粉末", "kor": "분말"},
            {"yomigana": "こむぎこ", "tango": "小麦粉", "kor": "밀가루"},
            {"yomigana": "かふんしょう", "tango": "花粉症", "kor": "꽃가루알레르기"},
            {"yomigana": "ざせき", "tango": "座席", "kor": "좌석"},
            {"yomigana": "だんしょう", "tango": "談笑", "kor": "담소"},
            {"yomigana": "わらう", "tango": "笑う", "kor": "웃다"},
            {"yomigana": "しそん", "tango": "子孫", "kor": "자손"},
            {"yomigana": "まご", "tango": "孫", "kor": "손자"},
            {"yomigana": "あんない", "tango": "案内", "kor": "안내"},
            {"yomigana": "ていあん", "tango": "提案", "kor": "제안"},
            {"yomigana": "にゅうよく", "tango": "入浴", "kor": "입욕"},
            {"yomigana": "よくしつ", "tango": "浴室", "kor": "욕실"},
            {"yomigana": "あびる", "tango": "浴びる", "kor": "씻다"},
            {"yomigana": "ざんねん", "tango": "残念", "kor": "유감"},
            {"yomigana": "のこる", "tango": "残る", "kor": "남겨지다"},
            {"yomigana": "のこす", "tango": "残す", "kor": "남기다"},
            {"yomigana": "しゃっきん", "tango": "借金", "kor": "빚"},
            {"yomigana": "かりる", "tango": "借りる", "kor": "빌리다"},
            {"yomigana": "さつじん", "tango": "殺人", "kor": "살인"},
            {"yomigana": "じさつ", "tango": "自殺", "kor": "자살"},
            {"yomigana": "さっとう", "tango": "殺到", "kor": "쇄도"},
            {"yomigana": "ころす", "tango": "殺す", "kor": "죽이다"},
        ]
    },
    "0603": {
        "label": "6월 3일",
        "pages": "69, 70",
        "words": [
            {"yomigana": "さべつ", "tango": "差別", "kor": "차별"},
            {"yomigana": "じさ", "tango": "時差", "kor": "시차"},
            {"yomigana": "さす", "tango": "差す", "kor": "가리다/꽂다"},
            {"yomigana": "そうこ", "tango": "倉庫", "kor": "창고"},
            {"yomigana": "くら", "tango": "倉", "kor": "곳간/창고"},
            {"yomigana": "とくべつ", "tango": "特別", "kor": "특별"},
            {"yomigana": "とくせい", "tango": "特性", "kor": "특성"},
            {"yomigana": "うんこう", "tango": "運航", "kor": "운항"},
            {"yomigana": "こうろ", "tango": "航路", "kor": "항로"},
            {"yomigana": "がいちゅう", "tango": "害虫", "kor": "해충"},
            {"yomigana": "ひがい", "tango": "被害", "kor": "피해"},
            {"yomigana": "きこう", "tango": "気候", "kor": "기후"},
            {"yomigana": "きょうくん", "tango": "教訓", "kor": "교훈"},
            {"yomigana": "くんよみ", "tango": "訓読み", "kor": "훈독"},
            {"yomigana": "おんよみ", "tango": "音読み", "kor": "음독"},
            {"yomigana": "けんこう", "tango": "健康", "kor": "건강"},
            {"yomigana": "ほけんじょ", "tango": "保健所", "kor": "보건소"},
            {"yomigana": "すこやかだ", "tango": "健やかだ", "kor": "건강하다"},
            {"yomigana": "きかい", "tango": "機械", "kor": "기계"},
            {"yomigana": "きゅうきゅう", "tango": "救急", "kor": "구급"},
            {"yomigana": "すくう", "tango": "救う", "kor": "구하다"},
            {"yomigana": "せいどう", "tango": "聖堂", "kor": "성당"},
            {"yomigana": "とくいだ", "tango": "得意だ", "kor": "잘하다"},
            {"yomigana": "せっとく", "tango": "説得", "kor": "설득"},
            {"yomigana": "なっとく", "tango": "納得", "kor": "납득"},
            {"yomigana": "える", "tango": "得る", "kor": "얻다"},
            {"yomigana": "たいりく", "tango": "大陸", "kor": "대륙"},
            {"yomigana": "りくじょう", "tango": "陸上", "kor": "육상"},
            {"yomigana": "きぼう", "tango": "希望", "kor": "희망"},
            {"yomigana": "のぞむ", "tango": "望む", "kor": "바라다"},
            {"yomigana": "ふくし", "tango": "副詞", "kor": "부사"},
            {"yomigana": "ふくそうり", "tango": "副総理", "kor": "부총리"},
        ]
    },
    "0604": {
        "label": "6월 4일",
        "pages": "71, 72",
        "words": [
            {"yomigana": "せいさん", "tango": "生産", "kor": "생산"},
            {"yomigana": "うむ", "tango": "産む", "kor": "낳다"},
            {"yomigana": "うまれる", "tango": "産まれる", "kor": "태어나다"},
            {"yomigana": "らんそう", "tango": "卵巣", "kor": "난소"},
            {"yomigana": "す", "tango": "巣", "kor": "둥지"},
            {"yomigana": "がっしょう", "tango": "合唱", "kor": "합창"},
            {"yomigana": "となえる", "tango": "唱える", "kor": "외치다"},
            {"yomigana": "やさい", "tango": "野菜", "kor": "야채"},
            {"yomigana": "なのはな", "tango": "菜の花", "kor": "유채꽃"},
            {"yomigana": "せいけつ", "tango": "清潔", "kor": "청결"},
            {"yomigana": "せいさん", "tango": "清算", "kor": "청산"},
            {"yomigana": "きよい", "tango": "清い", "kor": "맑다"},
            {"yomigana": "ていし", "tango": "停止", "kor": "정지"},
            {"yomigana": "ていしゃ", "tango": "停車", "kor": "정차"},
            {"yomigana": "そくめん", "tango": "側面", "kor": "측면"},
            {"yomigana": "うちがわ", "tango": "内側", "kor": "내측"},
            {"yomigana": "そとがわ", "tango": "外側", "kor": "외측"},
            {"yomigana": "しっぱい", "tango": "失敗", "kor": "실패"},
            {"yomigana": "しょうはい", "tango": "勝敗", "kor": "승패"},
            {"yomigana": "やぶれる", "tango": "敗れる", "kor": "지다"},
            {"yomigana": "でんぴょう", "tango": "伝票", "kor": "전표"},
            {"yomigana": "とうひょう", "tango": "投票", "kor": "투표"},
            {"yomigana": "かへい", "tango": "貨幣", "kor": "화폐"},
            {"yomigana": "かもつ", "tango": "貨物", "kor": "화물"},
            {"yomigana": "しがいち", "tango": "市街地", "kor": "시가지"},
            {"yomigana": "かいどう", "tango": "街道", "kor": "가도"},
            {"yomigana": "まち", "tango": "街", "kor": "거리"},
            {"yomigana": "しかく", "tango": "視覚", "kor": "시각"},
            {"yomigana": "さっかく", "tango": "錯覚", "kor": "착각"},
            {"yomigana": "おぼえる", "tango": "覚える", "kor": "기억하다"},
            {"yomigana": "けつろん", "tango": "結論", "kor": "결론"},
            {"yomigana": "けっか", "tango": "結果", "kor": "결과"},
            {"yomigana": "けっこん", "tango": "結婚", "kor": "결혼"},
            {"yomigana": "むすぶ", "tango": "結ぶ", "kor": "묶다/잇다"},
            {"yomigana": "けいき", "tango": "景気", "kor": "경기"},
            {"yomigana": "けしき", "tango": "景色", "kor": "경치"},
            {"yomigana": "ほっきょく", "tango": "北極", "kor": "북극"},
            {"yomigana": "なんきょく", "tango": "南極", "kor": "남극"},
            {"yomigana": "きゅうりょう", "tango": "給料", "kor": "급료"},
            {"yomigana": "しきゅう", "tango": "支給", "kor": "지급"},
            {"yomigana": "じきゅう", "tango": "時給", "kor": "시급"},
        ]
    },
    "0609": {
        "label": "6월 9일",
        "pages": "73, 74",
        "words": [
            {"yomigana": "はいたつ", "tango": "配達", "kor": "배달"},
            {"yomigana": "とうたつ", "tango": "到達", "kor": "도달"},
            {"yomigana": "ぐんたい", "tango": "軍隊", "kor": "군대"},
            {"yomigana": "にゅうたい", "tango": "入隊", "kor": "입대"},
            {"yomigana": "そくりょう", "tango": "測量", "kor": "측량"},
            {"yomigana": "ぶつりょう", "tango": "物量", "kor": "물량"},
            {"yomigana": "ぶんりょう", "tango": "分量", "kor": "분량"},
            {"yomigana": "はかる", "tango": "量る", "kor": "재다"},
            {"yomigana": "まんぞく", "tango": "満足", "kor": "만족"},
            {"yomigana": "ふまん", "tango": "不満", "kor": "불만"},
            {"yomigana": "みちる", "tango": "満ちる", "kor": "넘치다"},
            {"yomigana": "うむ", "tango": "有無", "kor": "유무"},
            {"yomigana": "むり", "tango": "無理", "kor": "무리"},
            {"yomigana": "ない", "tango": "無い", "kor": "없다"},
            {"yomigana": "はかせ", "tango": "博士", "kor": "박사"},
            {"yomigana": "はくぶつかん", "tango": "博物館", "kor": "박물관"},
            {"yomigana": "はくらんかい", "tango": "博覧会", "kor": "박람회"},
            {"yomigana": "ごはん", "tango": "ご飯", "kor": "밥"},
            {"yomigana": "ゆうはん", "tango": "夕飯", "kor": "저녁밥"},
            {"yomigana": "めし", "tango": "飯", "kor": "밥"},
            {"yomigana": "がくひ", "tango": "学費", "kor": "학비"},
            {"yomigana": "けいひ", "tango": "経費", "kor": "경비"},
            {"yomigana": "ひよう", "tango": "費用", "kor": "비용"},
            {"yomigana": "ついやす", "tango": "費やす", "kor": "소비하다"},
            {"yomigana": "かいさん", "tango": "解散", "kor": "해산"},
            {"yomigana": "さんぽ", "tango": "散歩", "kor": "산책"},
            {"yomigana": "ちる", "tango": "散る", "kor": "떨어지다"},
            {"yomigana": "ちらす", "tango": "散らす", "kor": "어지르다"},
            {"yomigana": "いんしょう", "tango": "印象", "kor": "인상"},
            {"yomigana": "げんしょう", "tango": "現象", "kor": "현상"},
            {"yomigana": "ぞう", "tango": "象", "kor": "코끼리"},
            {"yomigana": "しょうしつ", "tango": "焼失", "kor": "소실"},
            {"yomigana": "ねんしょう", "tango": "燃焼", "kor": "연소"},
            {"yomigana": "やく", "tango": "焼く", "kor": "태우다"},
            {"yomigana": "じゅんじょ", "tango": "順序", "kor": "순서"},
            {"yomigana": "じゅんちょう", "tango": "順調", "kor": "순조"},
            {"yomigana": "しぜん", "tango": "自然", "kor": "자연"},
            {"yomigana": "とうぜん", "tango": "当然", "kor": "당연"},
            {"yomigana": "てんねん", "tango": "天然", "kor": "천연"},
            {"yomigana": "ちょきん", "tango": "貯金", "kor": "저금"},
            {"yomigana": "さいしょ", "tango": "最初", "kor": "최초"},
            {"yomigana": "さいだい", "tango": "最大", "kor": "최대"},
            {"yomigana": "もっとも", "tango": "最も", "kor": "가장"},
            {"yomigana": "きどあいらく", "tango": "喜怒哀楽", "kor": "희노애락"},
            {"yomigana": "よろこぶ", "tango": "喜ぶ", "kor": "기뻐하다"},
        ]
    },
    "0610": {
        "label": "6월 10일",
        "pages": "75, 76",
        "words": [
            {"yomigana": "ろうどう", "tango": "労働", "kor": "노동"},
            {"yomigana": "はたらく", "tango": "働く", "kor": "일하다"},
            {"yomigana": "じしょ", "tango": "辞書", "kor": "사전"},
            {"yomigana": "じたい", "tango": "辞退", "kor": "사퇴"},
            {"yomigana": "やめる", "tango": "辞める", "kor": "그만두다"},
            {"yomigana": "けいぞく", "tango": "継続", "kor": "계속"},
            {"yomigana": "せつぞく", "tango": "接続", "kor": "접속"},
            {"yomigana": "れんぞく", "tango": "連続", "kor": "연속"},
            {"yomigana": "つづく", "tango": "続く", "kor": "계속되다"},
            {"yomigana": "つづける", "tango": "続ける", "kor": "계속하다"},
            {"yomigana": "しけん", "tango": "試験", "kor": "시험"},
            {"yomigana": "しちゃく", "tango": "試着", "kor": "시착"},
            {"yomigana": "こころみる", "tango": "試みる", "kor": "시험하다"},
            {"yomigana": "ためす", "tango": "試す", "kor": "시험하다"},
            {"yomigana": "あいじょう", "tango": "愛情", "kor": "애정"},
            {"yomigana": "れんあい", "tango": "恋愛", "kor": "연애"},
            {"yomigana": "えんぶん", "tango": "塩分", "kor": "염분"},
            {"yomigana": "しょくえん", "tango": "食塩", "kor": "식염"},
            {"yomigana": "しお", "tango": "塩", "kor": "소금"},
            {"yomigana": "いちょう", "tango": "胃腸", "kor": "위장"},
            {"yomigana": "せんそう", "tango": "戦争", "kor": "전쟁"},
            {"yomigana": "たたかう", "tango": "戦う", "kor": "싸우다"},
            {"yomigana": "せつやく", "tango": "節約", "kor": "절약"},
            {"yomigana": "きせつ", "tango": "季節", "kor": "계절"},
            {"yomigana": "おせちりょうり", "tango": "お節料理", "kor": "설명절음식"},
            {"yomigana": "ふし", "tango": "節", "kor": "마디"},
            {"yomigana": "しょうめい", "tango": "照明", "kor": "조명"},
            {"yomigana": "たいしょう", "tango": "対照", "kor": "대조"},
            {"yomigana": "てる", "tango": "照る", "kor": "비치다"},
            {"yomigana": "てらす", "tango": "照らす", "kor": "비추다"},
            {"yomigana": "いち", "tango": "位置", "kor": "위치"},
            {"yomigana": "ほうち", "tango": "放置", "kor": "방치"},
            {"yomigana": "おく", "tango": "置く", "kor": "두다"},
            {"yomigana": "かんり", "tango": "管理", "kor": "관리"},
            {"yomigana": "かんけい", "tango": "関係", "kor": "관계"},
            {"yomigana": "きかん", "tango": "機関", "kor": "기관"},
            {"yomigana": "きしゅ", "tango": "旗手", "kor": "기수"},
            {"yomigana": "はた", "tango": "旗", "kor": "깃발"},
            {"yomigana": "けいれき", "tango": "経歴", "kor": "경력"},
            {"yomigana": "れきし", "tango": "歴史", "kor": "역사"},
            {"yomigana": "せつめい", "tango": "説明", "kor": "설명"},
            {"yomigana": "とく", "tango": "説く", "kor": "이야기하다"},
        ]
    },
    "0611": {
        "label": "6월 11일",
        "pages": "77, 78",
        "words": [
            {"yomigana": "ぎょぎょう", "tango": "漁業", "kor": "어업"},
            {"yomigana": "ぎょせん", "tango": "漁船", "kor": "어선"},
            {"yomigana": "りょうし", "tango": "漁師", "kor": "어부"},
            {"yomigana": "あんせい", "tango": "安静", "kor": "안정"},
            {"yomigana": "しずかだ", "tango": "静かだ", "kor": "조용하다"},
            {"yomigana": "しゅもく", "tango": "種目", "kor": "종목"},
            {"yomigana": "しゅるい", "tango": "種類", "kor": "종류"},
            {"yomigana": "たね", "tango": "種", "kor": "종자"},
            {"yomigana": "かんさつ", "tango": "観察", "kor": "관찰"},
            {"yomigana": "けいさつ", "tango": "警察", "kor": "경찰"},
            {"yomigana": "かだい", "tango": "課題", "kor": "과제"},
            {"yomigana": "うつわ", "tango": "器", "kor": "그릇"},
            {"yomigana": "がっき", "tango": "楽器", "kor": "악기"},
            {"yomigana": "しょっき", "tango": "食器", "kor": "식기"},
            {"yomigana": "しゃりん", "tango": "車輪", "kor": "차륜"},
            {"yomigana": "ゆびわ", "tango": "指輪", "kor": "반지"},
            {"yomigana": "かんしょう", "tango": "鑑賞", "kor": "감상"},
            {"yomigana": "しょうきん", "tango": "賞金", "kor": "상금"},
            {"yomigana": "せんきょ", "tango": "選挙", "kor": "선거"},
            {"yomigana": "せんたく", "tango": "選択", "kor": "선택"},
            {"yomigana": "えらぶ", "tango": "選ぶ", "kor": "고르다"},
            {"yomigana": "えいよう", "tango": "栄養", "kor": "영양"},
            {"yomigana": "きょうよう", "tango": "教養", "kor": "교양"},
            {"yomigana": "ようせい", "tango": "養成", "kor": "양성"},
            {"yomigana": "やしなう", "tango": "養う", "kor": "기르다"},
            {"yomigana": "すうおく", "tango": "数億", "kor": "수억"},
            {"yomigana": "ねっしん", "tango": "熱心", "kor": "열심"},
            {"yomigana": "かねつ", "tango": "過熱", "kor": "과열"},
            {"yomigana": "ねつ", "tango": "熱", "kor": "열"},
            {"yomigana": "あつい", "tango": "熱い", "kor": "뜨겁다"},
            {"yomigana": "もくひょう", "tango": "目標", "kor": "목표"},
            {"yomigana": "ひょうじゅんご", "tango": "標準語", "kor": "표준어"},
            {"yomigana": "きかい", "tango": "機械", "kor": "기계"},
            {"yomigana": "どうき", "tango": "動機", "kor": "동기"},
            {"yomigana": "きろく", "tango": "記録", "kor": "기록"},
            {"yomigana": "ろくおん", "tango": "録音", "kor": "녹음"},
            {"yomigana": "めんせき", "tango": "面積", "kor": "면적"},
            {"yomigana": "つむ", "tango": "積む", "kor": "쌓다"},
            {"yomigana": "つもる", "tango": "積もる", "kor": "쌓이다"},
        ]
    },
    "0616": {
        "label": "6월 16일",
        "pages": "79, 80",
        "words": [
            {"yomigana": "かんこう", "tango": "観光", "kor": "관광"},
            {"yomigana": "かんさつ", "tango": "観察", "kor": "관찰"},
            {"yomigana": "かんそく", "tango": "観測", "kor": "관측"},
            {"yomigana": "しゅるい", "tango": "種類", "kor": "종류"},
            {"yomigana": "じんるい", "tango": "人類", "kor": "인류"},
            {"yomigana": "けいけん", "tango": "経験", "kor": "경험"},
            {"yomigana": "しけん", "tango": "試験", "kor": "시험"},
            {"yomigana": "たいけん", "tango": "体験", "kor": "체험"},
            {"yomigana": "かくだいきょう", "tango": "拡大鏡", "kor": "확대경"},
            {"yomigana": "かがみ", "tango": "鏡", "kor": "거울"},
            {"yomigana": "がんしょ", "tango": "願書", "kor": "원서"},
            {"yomigana": "ねんがん", "tango": "念願", "kor": "염원"},
            {"yomigana": "ねがう", "tango": "願う", "kor": "바라다"},
            {"yomigana": "きょうそう", "tango": "競走", "kor": "경주"},
            {"yomigana": "けいば", "tango": "競馬", "kor": "경마"},
            {"yomigana": "きそう", "tango": "競う", "kor": "경쟁하다"},
            {"yomigana": "ぎいん", "tango": "議員", "kor": "의원"},
            {"yomigana": "ぎかい", "tango": "議会", "kor": "의회"},
            {"yomigana": "きょうぎ", "tango": "協議", "kor": "협의"},
            {"yomigana": "えいきゅう", "tango": "永久", "kor": "영구"},
            {"yomigana": "ひさしい", "tango": "久しい", "kor": "오랜만이다"},
            {"yomigana": "たいきゅう", "tango": "耐久", "kor": "내구"},
            {"yomigana": "ぶっきょう", "tango": "仏教", "kor": "불교"},
            {"yomigana": "ほとけ", "tango": "仏", "kor": "부처"},
            {"yomigana": "たいひ", "tango": "対比", "kor": "대비"},
            {"yomigana": "ひりつ", "tango": "比率", "kor": "비율"},
            {"yomigana": "くらべる", "tango": "比べる", "kor": "비교하다"},
            {"yomigana": "しえん", "tango": "支援", "kor": "지원"},
            {"yomigana": "しじ", "tango": "支持", "kor": "지지"},
            {"yomigana": "ささえる", "tango": "支える", "kor": "지지하다"},
            {"yomigana": "かけつ", "tango": "可決", "kor": "가결"},
            {"yomigana": "かのう", "tango": "可能", "kor": "가능"},
            {"yomigana": "かんこうぶつ", "tango": "刊行物", "kor": "간행물"},
            {"yomigana": "しゅうかん", "tango": "週刊", "kor": "주간"},
            {"yomigana": "くとうてん", "tango": "句読点", "kor": "구두점"},
            {"yomigana": "もんく", "tango": "文句", "kor": "불평"},
            {"yomigana": "きゅうらい", "tango": "旧来", "kor": "종래"},
            {"yomigana": "はんざい", "tango": "犯罪", "kor": "범죄"},
            {"yomigana": "はんにん", "tango": "犯人", "kor": "범인"},
            {"yomigana": "おかす", "tango": "犯す", "kor": "저지르다"},
        ]
    },
    "0617": {
        "label": "6월 17일",
        "pages": "81, 82",
        "words": [
            {"yomigana": "あつりょく", "tango": "圧力", "kor": "압력"},
            {"yomigana": "きあつ", "tango": "気圧", "kor": "기압"},
            {"yomigana": "はいふ", "tango": "配布", "kor": "배포"},
            {"yomigana": "ぬの", "tango": "布", "kor": "천"},
            {"yomigana": "かめん", "tango": "仮面", "kor": "가면"},
            {"yomigana": "かせつ", "tango": "仮設", "kor": "가설"},
            {"yomigana": "けびょう", "tango": "仮病", "kor": "꾀병"},
            {"yomigana": "えいえん", "tango": "永遠", "kor": "영원"},
            {"yomigana": "ながい", "tango": "永い", "kor": "영원하다"},
            {"yomigana": "じけん", "tango": "事件", "kor": "사건"},
            {"yomigana": "じょうけん", "tango": "条件", "kor": "조건"},
            {"yomigana": "ようけん", "tango": "用件", "kor": "용건"},
            {"yomigana": "だんけつ", "tango": "団結", "kor": "단결"},
            {"yomigana": "だんち", "tango": "団地", "kor": "단지"},
            {"yomigana": "ふとん", "tango": "布団", "kor": "이불"},
            {"yomigana": "どくぜつ", "tango": "毒舌", "kor": "독설"},
            {"yomigana": "した", "tango": "舌", "kor": "혀"},
            {"yomigana": "ねこじた", "tango": "猫舌", "kor": "고양이혀"},
            {"yomigana": "げんいん", "tango": "原因", "kor": "원인"},
            {"yomigana": "よる", "tango": "因る", "kor": "기인하다"},
            {"yomigana": "せきにん", "tango": "責任", "kor": "책임"},
            {"yomigana": "にんむ", "tango": "任務", "kor": "임무"},
            {"yomigana": "まかせる", "tango": "任せる", "kor": "맡기다"},
            {"yomigana": "さらいしゅう", "tango": "再来週", "kor": "다다음주"},
            {"yomigana": "さいど", "tango": "再度", "kor": "재차"},
            {"yomigana": "ふたたび", "tango": "再び", "kor": "재차"},
            {"yomigana": "げんざい", "tango": "現在", "kor": "현재"},
            {"yomigana": "そんざい", "tango": "存在", "kor": "존재"},
            {"yomigana": "ある", "tango": "在る", "kor": "있다"},
            {"yomigana": "きんこう", "tango": "均衡", "kor": "균형"},
            {"yomigana": "へいきん", "tango": "平均", "kor": "평균"},
            {"yomigana": "ぎじゅつ", "tango": "技術", "kor": "기술"},
            {"yomigana": "きょうぎ", "tango": "競技", "kor": "경기"},
            {"yomigana": "わざ", "tango": "技", "kor": "기술"},
            {"yomigana": "ぼうえい", "tango": "防衛", "kor": "방위"},
            {"yomigana": "よぼう", "tango": "予防", "kor": "예방"},
            {"yomigana": "ふせぐ", "tango": "防ぐ", "kor": "막다"},
            {"yomigana": "おうえん", "tango": "応援", "kor": "응원"},
            {"yomigana": "おうきゅう", "tango": "応急", "kor": "응급"},
            {"yomigana": "るいじ", "tango": "類似", "kor": "유사"},
            {"yomigana": "にる", "tango": "似る", "kor": "닮다"},
        ]
    },
    "0618": {
        "label": "6월 18일",
        "pages": "83, 84",
        "words": [
            {"yomigana": "しょうじょう", "tango": "症状", "kor": "증상"},
            {"yomigana": "しょうじょう", "tango": "賞状", "kor": "상장"},
            {"yomigana": "じょうたい", "tango": "状態", "kor": "상태"},
            {"yomigana": "じゅんじょ", "tango": "順序", "kor": "순서"},
            {"yomigana": "じょれつ", "tango": "序列", "kor": "서열"},
            {"yomigana": "じょろん", "tango": "序論", "kor": "서론"},
            {"yomigana": "よぶん", "tango": "余分", "kor": "여분"},
            {"yomigana": "よゆう", "tango": "余裕", "kor": "여유"},
            {"yomigana": "あまる", "tango": "余る", "kor": "남다"},
            {"yomigana": "かさい", "tango": "火災", "kor": "화재"},
            {"yomigana": "さいがい", "tango": "災害", "kor": "재해"},
            {"yomigana": "さいなん", "tango": "災難", "kor": "재난"},
            {"yomigana": "じょうけん", "tango": "条件", "kor": "조건"},
            {"yomigana": "いし", "tango": "意志", "kor": "의지"},
            {"yomigana": "しぼう", "tango": "志望", "kor": "지망"},
            {"yomigana": "こころざす", "tango": "志す", "kor": "뜻을 세우다"},
            {"yomigana": "こころざし", "tango": "志し", "kor": "의지"},
            {"yomigana": "かいそく", "tango": "快速", "kor": "쾌속"},
            {"yomigana": "こころよい", "tango": "快い", "kor": "상쾌하다"},
            {"yomigana": "はんけつ", "tango": "判決", "kor": "판결"},
            {"yomigana": "はんだん", "tango": "判断", "kor": "판단"},
            {"yomigana": "ひはん", "tango": "批判", "kor": "비판"},
            {"yomigana": "わかる", "tango": "判る", "kor": "알다/판명되다"},
            {"yomigana": "かかく", "tango": "価格", "kor": "가격"},
            {"yomigana": "ぶっか", "tango": "物価", "kor": "물가"},
            {"yomigana": "あたい", "tango": "価", "kor": "가치"},
            {"yomigana": "どうきょ", "tango": "同居", "kor": "동거"},
            {"yomigana": "いる", "tango": "居る", "kor": "있다"},
            {"yomigana": "にゅうじょうけん", "tango": "入場券", "kor": "입장권"},
            {"yomigana": "りょけん", "tango": "旅券", "kor": "여권"},
            {"yomigana": "ぶき", "tango": "武器", "kor": "무기"},
            {"yomigana": "むしゃ", "tango": "武者", "kor": "무사"},
            {"yomigana": "ひまん", "tango": "肥満", "kor": "비만"},
            {"yomigana": "ひりょう", "tango": "肥料", "kor": "비료"},
            {"yomigana": "ひじょうぐち", "tango": "非常口", "kor": "비상구"},
            {"yomigana": "ひなん", "tango": "非難", "kor": "비난"},
            {"yomigana": "こうしゃ", "tango": "校舎", "kor": "교사"},
            {"yomigana": "きしゅくしゃ", "tango": "寄宿舎", "kor": "기숙사"},
            {"yomigana": "せいかく", "tango": "性格", "kor": "성격"},
            {"yomigana": "せいべつ", "tango": "性別", "kor": "성별"},
            {"yomigana": "あいしょう", "tango": "相性", "kor": "상성"},
        ]
    },
    "0623": {
        "label": "6월 23일",
        "pages": "85, 86",
        "words": [
            {"yomigana": "べんごし", "tango": "弁護士", "kor": "변호사"},
            {"yomigana": "べんとう", "tango": "弁当", "kor": "도시락"},
            {"yomigana": "けいじ", "tango": "掲示", "kor": "게시"},
            {"yomigana": "しじ", "tango": "指示", "kor": "지시"},
            {"yomigana": "ひょうじ", "tango": "表示", "kor": "표시"},
            {"yomigana": "しめす", "tango": "示す", "kor": "나타내다"},
            {"yomigana": "じょじゅつ", "tango": "叙述", "kor": "서술"},
            {"yomigana": "のべる", "tango": "述べる", "kor": "진술하다"},
            {"yomigana": "しょうだく", "tango": "承諾", "kor": "승낙"},
            {"yomigana": "しょうにん", "tango": "承認", "kor": "승인"},
            {"yomigana": "うけたまわる", "tango": "承る", "kor": "받다/접수하다"},
            {"yomigana": "ぼうえき", "tango": "貿易", "kor": "무역"},
            {"yomigana": "ようい", "tango": "容易", "kor": "용이"},
            {"yomigana": "やさしい", "tango": "易しい", "kor": "쉽다"},
            {"yomigana": "おうらい", "tango": "往来", "kor": "왕래"},
            {"yomigana": "おうふく", "tango": "往復", "kor": "왕복"},
            {"yomigana": "せいげん", "tango": "制限", "kor": "제한"},
            {"yomigana": "せいど", "tango": "制度", "kor": "제도"},
            {"yomigana": "えだ", "tango": "枝", "kor": "가지"},
            {"yomigana": "ふさい", "tango": "夫妻", "kor": "부처"},
            {"yomigana": "つま", "tango": "妻", "kor": "처"},
            {"yomigana": "しょうたい", "tango": "招待", "kor": "초대"},
            {"yomigana": "まねく", "tango": "招く", "kor": "초대하다"},
            {"yomigana": "はんが", "tango": "版画", "kor": "판화"},
            {"yomigana": "しゅっぱん", "tango": "出版", "kor": "출판"},
            {"yomigana": "うんが", "tango": "運河", "kor": "운하"},
            {"yomigana": "かわ", "tango": "河", "kor": "강"},
            {"yomigana": "こうか", "tango": "効果", "kor": "효과"},
            {"yomigana": "こうのう", "tango": "効能", "kor": "효능"},
            {"yomigana": "きく", "tango": "効く", "kor": "효과가있다"},
            {"yomigana": "こしょう", "tango": "故障", "kor": "고장"},
            {"yomigana": "じこ", "tango": "事故", "kor": "사고"},
            {"yomigana": "ゆえ", "tango": "故", "kor": "까닭"},
            {"yomigana": "こどく", "tango": "孤独", "kor": "고독"},
            {"yomigana": "どくしん", "tango": "独身", "kor": "독신"},
            {"yomigana": "ひとり", "tango": "独り", "kor": "혼자"},
            {"yomigana": "めいろ", "tango": "迷路", "kor": "미로"},
            {"yomigana": "まよう", "tango": "迷う", "kor": "헤매다"},
        ]
    },
    "0624": {
        "label": "6월 24일",
        "pages": "87, 88",
        "words": [
            {"yomigana": "ほけん", "tango": "保険", "kor": "보험"},
            {"yomigana": "ほしょう", "tango": "保証", "kor": "보증"},
            {"yomigana": "たもつ", "tango": "保つ", "kor": "유지하다"},
            {"yomigana": "ぎゃくてん", "tango": "逆転", "kor": "역전"},
            {"yomigana": "ぎゃく", "tango": "逆", "kor": "역"},
            {"yomigana": "さからう", "tango": "逆らう", "kor": "거스르다"},
            {"yomigana": "せいけん", "tango": "政権", "kor": "정권"},
            {"yomigana": "せいじ", "tango": "政治", "kor": "정치"},
            {"yomigana": "そこく", "tango": "祖国", "kor": "조국"},
            {"yomigana": "そふ", "tango": "祖父", "kor": "조부"},
            {"yomigana": "そぼ", "tango": "祖母", "kor": "조모"},
            {"yomigana": "きそく", "tango": "規則", "kor": "규칙"},
            {"yomigana": "げんそく", "tango": "原則", "kor": "원칙"},
            {"yomigana": "じたい", "tango": "辞退", "kor": "사퇴"},
            {"yomigana": "たいがく", "tango": "退学", "kor": "퇴학"},
            {"yomigana": "げんかい", "tango": "限界", "kor": "한계"},
            {"yomigana": "げんてい", "tango": "限定", "kor": "한정"},
            {"yomigana": "せいげん", "tango": "制限", "kor": "제한"},
            {"yomigana": "かぎる", "tango": "限る", "kor": "한정하다"},
            {"yomigana": "こうせい", "tango": "厚生", "kor": "후생"},
            {"yomigana": "あつい", "tango": "厚い", "kor": "두껍다"},
            {"yomigana": "こうせいしょう", "tango": "厚生省", "kor": "후생성"},
            {"yomigana": "けんさ", "tango": "検査", "kor": "검사"},
            {"yomigana": "ちょうさ", "tango": "調査", "kor": "조사"},
            {"yomigana": "こじん", "tango": "個人", "kor": "개인"},
            {"yomigana": "ごうかく", "tango": "合格", "kor": "합격"},
            {"yomigana": "しかく", "tango": "資格", "kor": "자격"},
            {"yomigana": "こうさく", "tango": "耕作", "kor": "경작"},
            {"yomigana": "たがやす", "tango": "耕す", "kor": "경작하다"},
            {"yomigana": "ほんのう", "tango": "本能", "kor": "본능"},
            {"yomigana": "のうりょく", "tango": "能力", "kor": "능력"},
            {"yomigana": "りゅうがく", "tango": "留学", "kor": "유학"},
            {"yomigana": "るす", "tango": "留守", "kor": "부재"},
            {"yomigana": "とまる", "tango": "留まる", "kor": "머물다"},
            {"yomigana": "とめる", "tango": "留める", "kor": "만류하다"},
            {"yomigana": "おんし", "tango": "恩師", "kor": "은사"},
            {"yomigana": "きょうし", "tango": "教師", "kor": "교사"},
            {"yomigana": "しゅうり", "tango": "修理", "kor": "수리"},
        ]
    },
    "0625": {
        "label": "6월 25일",
        "pages": "89, 90",
        "words": [
            {"yomigana": "さんそ", "tango": "酸素", "kor": "산소"},
            {"yomigana": "そしつ", "tango": "素質", "kor": "소질"},
            {"yomigana": "すがお", "tango": "素顔", "kor": "맨얼굴"},
            {"yomigana": "おうか", "tango": "桜花", "kor": "벚꽃"},
            {"yomigana": "さくら", "tango": "桜", "kor": "벚꽃"},
            {"yomigana": "ようい", "tango": "容易", "kor": "용이"},
            {"yomigana": "ないよう", "tango": "内容", "kor": "내용"},
            {"yomigana": "おんじん", "tango": "恩人", "kor": "은인"},
            {"yomigana": "こうえき", "tango": "公益", "kor": "공익"},
            {"yomigana": "りえき", "tango": "利益", "kor": "이익"},
            {"yomigana": "ざいさん", "tango": "財産", "kor": "재산"},
            {"yomigana": "さいふ", "tango": "財布", "kor": "지갑"},
            {"yomigana": "かいぞう", "tango": "改造", "kor": "개조"},
            {"yomigana": "そうぞう", "tango": "創造", "kor": "창조"},
            {"yomigana": "つくる", "tango": "造る", "kor": "만들다"},
            {"yomigana": "はき", "tango": "破棄", "kor": "파기"},
            {"yomigana": "はそん", "tango": "破損", "kor": "파손"},
            {"yomigana": "とっぱ", "tango": "突破", "kor": "돌파"},
            {"yomigana": "やぶる", "tango": "破る", "kor": "찢다"},
            {"yomigana": "やぶれる", "tango": "破れる", "kor": "찢어지다"},
            {"yomigana": "どひょう", "tango": "土俵", "kor": "(스모)씨름판"},
            {"yomigana": "たわら", "tango": "俵", "kor": "섬"},
            {"yomigana": "けいえい", "tango": "経営", "kor": "경영"},
            {"yomigana": "けいざい", "tango": "経済", "kor": "경제"},
            {"yomigana": "けいゆ", "tango": "経由", "kor": "경유"},
            {"yomigana": "へる", "tango": "経る", "kor": "경과하다/경유하다"},
            {"yomigana": "きほん", "tango": "基本", "kor": "기본"},
            {"yomigana": "きそ", "tango": "基礎", "kor": "기초"},
            {"yomigana": "もとづく", "tango": "基づく", "kor": "기초로하다"},
            {"yomigana": "きしゅく", "tango": "寄宿", "kor": "기숙"},
            {"yomigana": "よる", "tango": "寄る", "kor": "들르다"},
            {"yomigana": "きせい", "tango": "規制", "kor": "규제"},
            {"yomigana": "きそく", "tango": "規則", "kor": "규칙"},
            {"yomigana": "きりつ", "tango": "規律", "kor": "규율"},
            {"yomigana": "けつだん", "tango": "決断", "kor": "결단"},
            {"yomigana": "ちゅうだん", "tango": "中断", "kor": "중단"},
            {"yomigana": "たつ", "tango": "断つ", "kor": "끊다"},
            {"yomigana": "ことわる", "tango": "断る", "kor": "거절하다"},
            {"yomigana": "しょうりゃく", "tango": "省略", "kor": "생략"},
            {"yomigana": "りゃくじ", "tango": "略字", "kor": "약어"},
            {"yomigana": "ぎむ", "tango": "義務", "kor": "의무"},
            {"yomigana": "じむ", "tango": "事務", "kor": "사무"},
            {"yomigana": "つとめる", "tango": "務める", "kor": "역할을 맡다"},
        ]
    },
    "0630": {
        "label": "6월 30일",
        "pages": "91, 92",
        "words": [
            {"yomigana": "ふうふ", "tango": "夫婦", "kor": "부부"},
            {"yomigana": "ひんぷ", "tango": "貧富", "kor": "빈부"},
            {"yomigana": "びんぼう", "tango": "貧乏", "kor": "궁핍"},
            {"yomigana": "まずしい", "tango": "貧しい", "kor": "가난하다"},
            {"yomigana": "じょうしき", "tango": "常識", "kor": "상식"},
            {"yomigana": "にちじょう", "tango": "日常", "kor": "일상"},
            {"yomigana": "つねに", "tango": "常に", "kor": "항상"},
            {"yomigana": "せつび", "tango": "設備", "kor": "설비"},
            {"yomigana": "せっけい", "tango": "設計", "kor": "설계"},
            {"yomigana": "もうける", "tango": "設ける", "kor": "설계하다"},
            {"yomigana": "いんそつ", "tango": "引率", "kor": "인솔"},
            {"yomigana": "そっちょく", "tango": "率直", "kor": "솔직"},
            {"yomigana": "のうりつ", "tango": "能率", "kor": "능률"},
            {"yomigana": "ひきいる", "tango": "率いる", "kor": "거느리다/인솔하다"},
            {"yomigana": "きょうじゅ", "tango": "教授", "kor": "교수"},
            {"yomigana": "じゅぎょう", "tango": "授業", "kor": "수업"},
            {"yomigana": "ぎじゅつ", "tango": "技術", "kor": "기술"},
            {"yomigana": "げいじゅつ", "tango": "芸術", "kor": "예술"},
            {"yomigana": "がんもく", "tango": "眼目", "kor": "안목"},
            {"yomigana": "まなこ", "tango": "眼", "kor": "눈알"},
            {"yomigana": "えきたい", "tango": "液体", "kor": "액체"},
            {"yomigana": "けつえきがた", "tango": "血液型", "kor": "혈액형"},
            {"yomigana": "いしょく", "tango": "移植", "kor": "이식"},
            {"yomigana": "いどう", "tango": "移動", "kor": "이동"},
            {"yomigana": "うつる", "tango": "移る", "kor": "움직이다"},
            {"yomigana": "うつす", "tango": "移す", "kor": "옮기다"},
            {"yomigana": "きんちょう", "tango": "緊張", "kor": "긴장"},
            {"yomigana": "しゅちょう", "tango": "主張", "kor": "주장"},
            {"yomigana": "はる", "tango": "張る", "kor": "늘리다"},
            {"yomigana": "せつぞく", "tango": "接続", "kor": "접속"},
            {"yomigana": "ちょくせつ", "tango": "直接", "kor": "직접"},
            {"yomigana": "じょうねつ", "tango": "情熱", "kor": "정열"},
            {"yomigana": "にんじょう", "tango": "人情", "kor": "인정"},
            {"yomigana": "なさけ", "tango": "情け", "kor": "정"},
            {"yomigana": "さいてん", "tango": "採点", "kor": "채점"},
            {"yomigana": "さいよう", "tango": "採用", "kor": "채용"},
            {"yomigana": "せきにん", "tango": "責任", "kor": "책임"},
            {"yomigana": "せきむ", "tango": "責務", "kor": "책무"},
            {"yomigana": "せめる", "tango": "責める", "kor": "책망하다"},
            {"yomigana": "きょか", "tango": "許可", "kor": "허가"},
            {"yomigana": "とっきょ", "tango": "特許", "kor": "특허"},
            {"yomigana": "ゆるす", "tango": "許す", "kor": "용서하다"},
        ]
    },
    "0701": {
        "label": "7월 1일",
        "pages": "93, 94",
        "words": [
            {"yomigana": "ほけん", "tango": "保険", "kor": "보험"},
            {"yomigana": "ぼうけん", "tango": "冒険", "kor": "모험"},
            {"yomigana": "けわしい", "tango": "険しい", "kor": "험악하다"},
            {"yomigana": "げんじつ", "tango": "現実", "kor": "현실"},
            {"yomigana": "げんしょう", "tango": "現象", "kor": "현상"},
            {"yomigana": "げんば", "tango": "現場", "kor": "현장"},
            {"yomigana": "あらわれる", "tango": "現れる", "kor": "나타나다"},
            {"yomigana": "あらわす", "tango": "現す", "kor": "나타내다"},
            {"yomigana": "こんざつ", "tango": "混雑", "kor": "혼잡"},
            {"yomigana": "こんらん", "tango": "混乱", "kor": "혼란"},
            {"yomigana": "まじる", "tango": "混じる", "kor": "섞이다"},
            {"yomigana": "まざる", "tango": "混ざる", "kor": "섞이다"},
            {"yomigana": "まぜる", "tango": "混ぜる", "kor": "섞다"},
            {"yomigana": "げんしょう", "tango": "減少", "kor": "감소"},
            {"yomigana": "さくげん", "tango": "削減", "kor": "삭감"},
            {"yomigana": "へる", "tango": "減る", "kor": "줄다"},
            {"yomigana": "へらす", "tango": "減らす", "kor": "줄이다"},
            {"yomigana": "けんさ", "tango": "検査", "kor": "검사"},
            {"yomigana": "てんけん", "tango": "点検", "kor": "점검"},
            {"yomigana": "かこ", "tango": "過去", "kor": "과거"},
            {"yomigana": "つうか", "tango": "通過", "kor": "통과"},
            {"yomigana": "あやまち", "tango": "過ち", "kor": "잘못"},
            {"yomigana": "すぎる", "tango": "過ぎる", "kor": "지나다"},
            {"yomigana": "すごす", "tango": "過ごす", "kor": "보내다"},
            {"yomigana": "たいよ", "tango": "貸与", "kor": "대여"},
            {"yomigana": "ちんたい", "tango": "賃貸", "kor": "임대"},
            {"yomigana": "かす", "tango": "貸す", "kor": "빌려주다"},
            {"yomigana": "ぼうえき", "tango": "貿易", "kor": "무역"},
            {"yomigana": "ほうこく", "tango": "報告", "kor": "보고"},
            {"yomigana": "ほうどう", "tango": "報道", "kor": "보도"},
            {"yomigana": "むくいる", "tango": "報いる", "kor": "갚다"},
            {"yomigana": "おうふく", "tango": "往復", "kor": "왕복"},
            {"yomigana": "ふっかつ", "tango": "復活", "kor": "부활"},
            {"yomigana": "ふくしゅう", "tango": "復習", "kor": "복습"},
            {"yomigana": "ほうふ", "tango": "豊富", "kor": "풍부"},
            {"yomigana": "かんび", "tango": "完備", "kor": "완비"},
            {"yomigana": "じゅんび", "tango": "準備", "kor": "준비"},
            {"yomigana": "そなえる", "tango": "備える", "kor": "준비하다"},
            {"yomigana": "そなわる", "tango": "備わる", "kor": "구비되다"},
            {"yomigana": "ぜいきん", "tango": "税金", "kor": "세금"},
            {"yomigana": "のうぜい", "tango": "納税", "kor": "납세"},
            {"yomigana": "きんぞく", "tango": "金属", "kor": "금속"},
            {"yomigana": "しょぞく", "tango": "所属", "kor": "소속"},
            {"yomigana": "うんえい", "tango": "運営", "kor": "운영"},
            {"yomigana": "えいぎょう", "tango": "営業", "kor": "영업"},
            {"yomigana": "けいえい", "tango": "経営", "kor": "경영"},
            {"yomigana": "いとなむ", "tango": "営む", "kor": "경영하다"},
            {"yomigana": "ぜつぼう", "tango": "絶望", "kor": "절망"},
            {"yomigana": "ぜったい", "tango": "絶対", "kor": "절대"},
            {"yomigana": "だんぜつ", "tango": "断絶", "kor": "단절"},
            {"yomigana": "たえる", "tango": "絶える", "kor": "끊어지다"},
            {"yomigana": "たつ", "tango": "絶つ", "kor": "끊다"},
        ]
    },
    "0702": {
        "label": "7월 2일",
        "pages": "95, 96",
        "words": [
            {"yomigana": "ていど", "tango": "程度", "kor": "정도"},
            {"yomigana": "にってい", "tango": "日程", "kor": "일정"},
            {"yomigana": "ほどほど", "tango": "程々", "kor": "정도껏"},
            {"yomigana": "ていきょう", "tango": "提供", "kor": "제공"},
            {"yomigana": "ていしゅつ", "tango": "提出", "kor": "제출"},
            {"yomigana": "ていじ", "tango": "提示", "kor": "제시"},
            {"yomigana": "しょうこ", "tango": "証拠", "kor": "증거"},
            {"yomigana": "しょうめい", "tango": "証明", "kor": "증명"},
            {"yomigana": "そくてい", "tango": "測定", "kor": "측정"},
            {"yomigana": "よそく", "tango": "予測", "kor": "예측"},
            {"yomigana": "はかる", "tango": "測る", "kor": "재다(각도 등)"},
            {"yomigana": "でんとう", "tango": "伝統", "kor": "전통"},
            {"yomigana": "とういつ", "tango": "統一", "kor": "통일"},
            {"yomigana": "とうけい", "tango": "統計", "kor": "통계"},
            {"yomigana": "こうひょう", "tango": "好評", "kor": "호평"},
            {"yomigana": "ひょうか", "tango": "評価", "kor": "평가"},
            {"yomigana": "しゅくが", "tango": "祝賀", "kor": "축하"},
            {"yomigana": "ねんがじょう", "tango": "年賀状", "kor": "연하장"},
            {"yomigana": "ぐんしゅう", "tango": "群衆", "kor": "군중"},
            {"yomigana": "ばつぐん", "tango": "抜群", "kor": "발군"},
            {"yomigana": "むれ", "tango": "群れ", "kor": "무리"},
            {"yomigana": "きんえん", "tango": "禁煙", "kor": "금연"},
            {"yomigana": "きんし", "tango": "禁止", "kor": "금지"},
            {"yomigana": "きんじる", "tango": "禁じる", "kor": "금하다"},
            {"yomigana": "かんぶ", "tango": "幹部", "kor": "간부"},
            {"yomigana": "かんじ", "tango": "幹事", "kor": "간사"},
            {"yomigana": "みき", "tango": "幹", "kor": "줄기"},
            {"yomigana": "たんこう", "tango": "炭鉱", "kor": "탄광"},
            {"yomigana": "あくむ", "tango": "悪夢", "kor": "악몽"},
            {"yomigana": "むちゅう", "tango": "夢中", "kor": "열중"},
            {"yomigana": "ゆめ", "tango": "夢", "kor": "꿈"},
            {"yomigana": "はかまいり", "tango": "墓参り", "kor": "성묘"},
            {"yomigana": "おはか", "tango": "お墓", "kor": "무덤"},
            {"yomigana": "しいく", "tango": "飼育", "kor": "사육"},
            {"yomigana": "かう", "tango": "飼う", "kor": "기르다"},
            {"yomigana": "しせい", "tango": "姿勢", "kor": "자세"},
            {"yomigana": "せいりょく", "tango": "勢力", "kor": "세력"},
            {"yomigana": "いきおい", "tango": "勢い", "kor": "기세"},
            {"yomigana": "そんがい", "tango": "損害", "kor": "손해"},
            {"yomigana": "そんしょう", "tango": "損傷", "kor": "손상"},
        ]
    },
    "0707": {
        "label": "7월 7일",
        "pages": "97, 98",
        "words": [
            {"yomigana": "よきん", "tango": "預金", "kor": "예금"},
            {"yomigana": "あずかる", "tango": "預かる", "kor": "맡다"},
            {"yomigana": "あずける", "tango": "預ける", "kor": "맡기다"},
            {"yomigana": "いぎ", "tango": "意義", "kor": "의의"},
            {"yomigana": "ぎり", "tango": "義理", "kor": "의리"},
            {"yomigana": "しかく", "tango": "資格", "kor": "자격"},
            {"yomigana": "しきん", "tango": "資金", "kor": "자금"},
            {"yomigana": "すいじゅん", "tango": "水準", "kor": "수준"},
            {"yomigana": "ひょうじゅん", "tango": "標準", "kor": "표준"},
            {"yomigana": "ざいあく", "tango": "罪悪", "kor": "죄악"},
            {"yomigana": "しゃざい", "tango": "謝罪", "kor": "사죄"},
            {"yomigana": "つみ", "tango": "罪", "kor": "죄"},
            {"yomigana": "ほうふ", "tango": "豊富", "kor": "풍부"},
            {"yomigana": "ゆたかだ", "tango": "豊かだ", "kor": "풍부하다"},
            {"yomigana": "かいせつ", "tango": "解説", "kor": "해설"},
            {"yomigana": "どっかい", "tango": "読解", "kor": "독해"},
            {"yomigana": "りかい", "tango": "理解", "kor": "이해"},
            {"yomigana": "とく", "tango": "解く", "kor": "풀다"},
            {"yomigana": "とかす", "tango": "解かす", "kor": "녹이다"},
            {"yomigana": "かんきょう", "tango": "環境", "kor": "환경"},
            {"yomigana": "こっきょう", "tango": "国境", "kor": "국경"},
            {"yomigana": "さかい", "tango": "境", "kor": "경계"},
            {"yomigana": "こうぞう", "tango": "構造", "kor": "구조"},
            {"yomigana": "かまう", "tango": "構う", "kor": "상관하다"},
            {"yomigana": "かまえる", "tango": "構える", "kor": "꾸미다"},
            {"yomigana": "かんしゅう", "tango": "慣習", "kor": "관습"},
            {"yomigana": "しゅうかん", "tango": "習慣", "kor": "습관"},
            {"yomigana": "なれる", "tango": "慣れる", "kor": "익숙해지다"},
            {"yomigana": "ならす", "tango": "慣らす", "kor": "순응시키다"},
            {"yomigana": "どうとく", "tango": "道徳", "kor": "도덕"},
            {"yomigana": "どう", "tango": "銅メダル", "kor": "동메달"},
            {"yomigana": "だいとうりょう", "tango": "大統領", "kor": "대통령"},
            {"yomigana": "ようりょう", "tango": "要領", "kor": "요령"},
            {"yomigana": "もめん", "tango": "木綿", "kor": "무명"},
            {"yomigana": "わた", "tango": "綿", "kor": "목화솜"},
            {"yomigana": "ふくざつ", "tango": "複雑", "kor": "복잡"},
            {"yomigana": "ふくすう", "tango": "複数", "kor": "복수"},
            {"yomigana": "さんそ", "tango": "酸素", "kor": "산소"},
            {"yomigana": "たんさん", "tango": "炭酸", "kor": "탄산"},
            {"yomigana": "すっぱい", "tango": "酸っぱい", "kor": "시다"},
        ]
    },
    "0708": {
        "label": "7월 8일",
        "pages": "99, 100",
        "words": [
            {"yomigana": "じつぞう", "tango": "実像", "kor": "실상"},
            {"yomigana": "そうぞう", "tango": "想像", "kor": "상상"},
            {"yomigana": "えんしゅつ", "tango": "演出", "kor": "연출"},
            {"yomigana": "えんぜつ", "tango": "演説", "kor": "연설"},
            {"yomigana": "こうえん", "tango": "公演", "kor": "공연"},
            {"yomigana": "えんじる", "tango": "演じる", "kor": "연기하다"},
            {"yomigana": "こんざつ", "tango": "混雑", "kor": "혼잡"},
            {"yomigana": "ざっし", "tango": "雑誌", "kor": "잡지"},
            {"yomigana": "かいてき", "tango": "快適", "kor": "쾌적"},
            {"yomigana": "てきとう", "tango": "適当", "kor": "적당"},
            {"yomigana": "きんせん", "tango": "金銭", "kor": "금전"},
            {"yomigana": "せんとう", "tango": "銭湯", "kor": "(공중)목욕탕"},
            {"yomigana": "こぜに", "tango": "小銭", "kor": "동전"},
            {"yomigana": "せいしん", "tango": "精神", "kor": "정신"},
            {"yomigana": "せいみつ", "tango": "精密", "kor": "정밀"},
            {"yomigana": "こくさい", "tango": "国際", "kor": "국제"},
            {"yomigana": "せいさく", "tango": "製作", "kor": "제작"},
            {"yomigana": "せいぞう", "tango": "製造", "kor": "제조"},
            {"yomigana": "がいこくせい", "tango": "外国製", "kor": "외국제"},
            {"yomigana": "ぞうか", "tango": "増加", "kor": "증가"},
            {"yomigana": "ふえる", "tango": "増える", "kor": "늘다"},
            {"yomigana": "ふやす", "tango": "増やす", "kor": "늘리다"},
            {"yomigana": "そうけい", "tango": "総計", "kor": "총계"},
            {"yomigana": "そうり", "tango": "総理", "kor": "총리"},
            {"yomigana": "けいたい", "tango": "形態", "kor": "형태"},
            {"yomigana": "たいど", "tango": "態度", "kor": "태도"},
            {"yomigana": "せいけつ", "tango": "清潔", "kor": "청결"},
            {"yomigana": "どうにゅう", "tango": "導入", "kor": "도입"},
            {"yomigana": "てきち", "tango": "敵地", "kor": "적지"},
            {"yomigana": "かたき", "tango": "敵", "kor": "원수"},
            {"yomigana": "しつりょう", "tango": "質量", "kor": "질량"},
            {"yomigana": "しちや", "tango": "質屋", "kor": "전당포"},
            {"yomigana": "さんせい", "tango": "賛成", "kor": "찬성"},
        ]
    },
    "0709": {
        "label": "7월 9일",
        "pages": "101, 102",
        "words": [
            {"yomigana": "へんしゅう", "tango": "編集", "kor": "편집"},
            {"yomigana": "あむ", "tango": "編む", "kor": "뜨다"},
            {"yomigana": "ぼうりょく", "tango": "暴力", "kor": "폭력"},
            {"yomigana": "ばくろ", "tango": "暴露", "kor": "폭로"},
            {"yomigana": "あばれる", "tango": "暴れる", "kor": "난폭하게굴다"},
            {"yomigana": "あばく", "tango": "暴く", "kor": "폭로하다"},
            {"yomigana": "かくじつ", "tango": "確実", "kor": "확실"},
            {"yomigana": "かくにん", "tango": "確認", "kor": "확인"},
            {"yomigana": "めいかく", "tango": "明確", "kor": "명확"},
            {"yomigana": "たしかだ", "tango": "確かだ", "kor": "확실하다"},
            {"yomigana": "たしかめる", "tango": "確かめる", "kor": "확인하다"},
            {"yomigana": "ねんりょう", "tango": "燃料", "kor": "연료"},
            {"yomigana": "もえる", "tango": "燃える", "kor": "타다"},
            {"yomigana": "もやす", "tango": "燃やす", "kor": "태우다"},
            {"yomigana": "ゆしゅつ", "tango": "輸出", "kor": "수출"},
            {"yomigana": "ゆにゅう", "tango": "輸入", "kor": "수입"},
            {"yomigana": "えいせい", "tango": "衛星", "kor": "위성"},
            {"yomigana": "じえいたい", "tango": "自衛隊", "kor": "자위대"},
            {"yomigana": "けんちく", "tango": "建築", "kor": "건축"},
            {"yomigana": "きずく", "tango": "築く", "kor": "쌓다"},
            {"yomigana": "きょうみ", "tango": "興味", "kor": "흥미"},
            {"yomigana": "かいこう", "tango": "開講", "kor": "개강"},
            {"yomigana": "こうぎ", "tango": "講義", "kor": "강의"},
            {"yomigana": "かんしゃ", "tango": "感謝", "kor": "감사"},
            {"yomigana": "あやまる", "tango": "謝る", "kor": "사과하다"},
            {"yomigana": "ぎょうせき", "tango": "業績", "kor": "업적"},
            {"yomigana": "じっせき", "tango": "実績", "kor": "실적"},
            {"yomigana": "きんがく", "tango": "金額", "kor": "금액"},
            {"yomigana": "ぜんがく", "tango": "全額", "kor": "전액"},
            {"yomigana": "ひたい", "tango": "額", "kor": "이마"},
            {"yomigana": "しゅうしょく", "tango": "就職", "kor": "취직"},
            {"yomigana": "しょくば", "tango": "職場", "kor": "직장"},
            {"yomigana": "そしき", "tango": "組織", "kor": "조직"},
            {"yomigana": "おる", "tango": "織る", "kor": "짜다"},
            {"yomigana": "いしき", "tango": "意識", "kor": "의식"},
            {"yomigana": "にんしき", "tango": "認識", "kor": "인식"},
            {"yomigana": "かいご", "tango": "介護", "kor": "간호"},
            {"yomigana": "ほご", "tango": "保護", "kor": "보호"},
        ]
    },
    "0714": {
        "label": "7월 14일",
        "pages": "103, 104",
        "words": [
            {"yomigana": "じゃっかん", "tango": "若干", "kor": "약간"},
            {"yomigana": "かんしょう", "tango": "干渉", "kor": "간섭"},
            {"yomigana": "ほす", "tango": "干す", "kor": "널다"},
            {"yomigana": "じこ", "tango": "自己", "kor": "자기"},
            {"yomigana": "しぼう", "tango": "死亡", "kor": "사망"},
            {"yomigana": "もうじゃ", "tango": "亡者", "kor": "망자"},
            {"yomigana": "いっすん", "tango": "一寸", "kor": "한치"},
            {"yomigana": "すんぽう", "tango": "寸法", "kor": "치수"},
            {"yomigana": "しゅうかく", "tango": "収穫", "kor": "수확"},
            {"yomigana": "しゅうにゅう", "tango": "収入", "kor": "수입"},
            {"yomigana": "おさまる", "tango": "収まる", "kor": "걷히다"},
            {"yomigana": "おさめる", "tango": "収める", "kor": "거두다"},
            {"yomigana": "じんあい", "tango": "仁愛", "kor": "인애"},
            {"yomigana": "しゃくど", "tango": "尺度", "kor": "척도"},
            {"yomigana": "かたおもい", "tango": "片思い", "kor": "짝사랑"},
            {"yomigana": "だんぺん", "tango": "断片", "kor": "단편"},
            {"yomigana": "ようちえん", "tango": "幼稚園", "kor": "유치원"},
            {"yomigana": "おさない", "tango": "幼い", "kor": "어리다"},
            {"yomigana": "いっさつ", "tango": "一冊", "kor": "한 권"},
            {"yomigana": "しょぶん", "tango": "処分", "kor": "처분"},
            {"yomigana": "ところ", "tango": "処", "kor": "곳"},
            {"yomigana": "とちょう", "tango": "都庁", "kor": "도청"},
            {"yomigana": "ちょうしゃ", "tango": "庁舎", "kor": "청사"},
            {"yomigana": "あな", "tango": "穴", "kor": "구멍"},
            {"yomigana": "つくえ", "tango": "机", "kor": "책상"},
            {"yomigana": "うちゅう", "tango": "宇宙", "kor": "우주"},
            {"yomigana": "きき", "tango": "危機", "kor": "위기"},
            {"yomigana": "きけん", "tango": "危険", "kor": "위험"},
            {"yomigana": "あぶない", "tango": "危ない", "kor": "위험하다"},
            {"yomigana": "あやうい", "tango": "危うい", "kor": "위험하다"},
        ]
    },
    "0715": {
        "label": "7월 15일",
        "pages": "105, 106",
        "words": [
            {"yomigana": "そんざい", "tango": "存在", "kor": "존재"},
            {"yomigana": "ほぞん", "tango": "保存", "kor": "보존"},
            {"yomigana": "しきゅう", "tango": "至急", "kor": "지급"},
            {"yomigana": "いたる", "tango": "至る", "kor": "이르다"},
            {"yomigana": "じゅうたく", "tango": "住宅", "kor": "주택"},
            {"yomigana": "たくはいびん", "tango": "宅配便", "kor": "택배"},
            {"yomigana": "こうごう", "tango": "皇后", "kor": "황후"},
            {"yomigana": "せっかい", "tango": "石灰", "kor": "석회"},
            {"yomigana": "はい", "tango": "灰", "kor": "재"},
            {"yomigana": "こきゅう", "tango": "呼吸", "kor": "호흡"},
            {"yomigana": "きゅうしゅう", "tango": "吸収", "kor": "흡수"},
            {"yomigana": "すう", "tango": "吸う", "kor": "들이마시다"},
            {"yomigana": "けいれつ", "tango": "系列", "kor": "계열"},
            {"yomigana": "ひんこん", "tango": "貧困", "kor": "빈곤"},
            {"yomigana": "こんなん", "tango": "困難", "kor": "곤란"},
            {"yomigana": "こまる", "tango": "困る", "kor": "곤란하다"},
            {"yomigana": "じゅせいらん", "tango": "受精卵", "kor": "수정란"},
            {"yomigana": "なまたまご", "tango": "生卵", "kor": "날달걀"},
            {"yomigana": "らんぼう", "tango": "乱暴", "kor": "난폭"},
            {"yomigana": "はんらん", "tango": "反乱", "kor": "반란"},
            {"yomigana": "みだれる", "tango": "乱れる", "kor": "흐트러지다"},
            {"yomigana": "みだす", "tango": "乱す", "kor": "어지럽히다"},
            {"yomigana": "けんぼうしょう", "tango": "健忘症", "kor": "건망증"},
            {"yomigana": "ぼうねんかい", "tango": "忘年会", "kor": "망년회"},
            {"yomigana": "わすれる", "tango": "忘れる", "kor": "잊다"},
            {"yomigana": "ひてい", "tango": "否定", "kor": "부정"},
            {"yomigana": "ひにん", "tango": "否認", "kor": "부인"},
            {"yomigana": "ひひょう", "tango": "批評", "kor": "비평"},
            {"yomigana": "ひはん", "tango": "批判", "kor": "비판"},
            {"yomigana": "しふく", "tango": "私服", "kor": "사복"},
            {"yomigana": "しりつ", "tango": "私立", "kor": "사립"},
            {"yomigana": "わたし/わたくし", "tango": "私", "kor": "나,저"},
            {"yomigana": "がまん", "tango": "我慢", "kor": "참음"},
            {"yomigana": "じが", "tango": "自我", "kor": "자아"},
            {"yomigana": "われわれ", "tango": "我々", "kor": "우리들"},
            {"yomigana": "わがや", "tango": "我が家", "kor": "우리집"},
            {"yomigana": "こうこう", "tango": "孝行", "kor": "효행"},
            {"yomigana": "ふこう", "tango": "不孝", "kor": "불효"},
            {"yomigana": "おやこうこう", "tango": "親孝行", "kor": "효도"},
        ]
    },
    "0716": {
        "label": "7월 16일",
        "pages": "107, 108",
        "words": [
            {"yomigana": "じこく", "tango": "時刻", "kor": "시각"},
            {"yomigana": "しんこく", "tango": "深刻", "kor": "심각"},
            {"yomigana": "ちこく", "tango": "遅刻", "kor": "지각"},
            {"yomigana": "きざむ", "tango": "刻む", "kor": "새기다/잘게썰다"},
            {"yomigana": "とどく", "tango": "届く", "kor": "도달하다"},
            {"yomigana": "とどける", "tango": "届ける", "kor": "보내다"},
            {"yomigana": "きょうきゅう", "tango": "供給", "kor": "공급"},
            {"yomigana": "ていきょう", "tango": "提供", "kor": "제공"},
            {"yomigana": "こども", "tango": "子供", "kor": "어린이"},
            {"yomigana": "たんとう", "tango": "担当", "kor": "담당"},
            {"yomigana": "ふたん", "tango": "負担", "kor": "부담"},
            {"yomigana": "ぶんたん", "tango": "分担", "kor": "분담"},
            {"yomigana": "になう", "tango": "担う", "kor": "짊어지다"},
            {"yomigana": "いちまい", "tango": "一枚", "kor": "한 장"},
            {"yomigana": "なんまい", "tango": "何枚", "kor": "몇 장"},
            {"yomigana": "さんぱい", "tango": "参拝", "kor": "참배"},
            {"yomigana": "へいこう", "tango": "並行", "kor": "병행"},
            {"yomigana": "へいれつ", "tango": "並列", "kor": "병렬"},
            {"yomigana": "ひとなみ", "tango": "人並", "kor": "평범/보통"},
            {"yomigana": "ならぶ", "tango": "並ぶ", "kor": "늘어서다"},
            {"yomigana": "ならべる", "tango": "並べる", "kor": "늘어놓다"},
            {"yomigana": "こくほう", "tango": "国宝", "kor": "국보"},
            {"yomigana": "ほうせき", "tango": "宝石", "kor": "보석"},
            {"yomigana": "たから", "tango": "宝", "kor": "보물"},
            {"yomigana": "すいちょく", "tango": "垂直", "kor": "수직"},
            {"yomigana": "たれる", "tango": "垂れる", "kor": "처지다"},
            {"yomigana": "たらす", "tango": "垂らす", "kor": "늘어뜨리다"},
            {"yomigana": "ろうにゃく", "tango": "老若", "kor": "노약"},
            {"yomigana": "ろうにゃくなんにょ", "tango": "老若男女", "kor": "남녀노소"},
            {"yomigana": "わかい", "tango": "若い", "kor": "젊다"},
            {"yomigana": "ぎゅうにゅう", "tango": "牛乳", "kor": "우유"},
            {"yomigana": "ぼにゅう", "tango": "母乳", "kor": "모유"},
            {"yomigana": "えんき", "tango": "延期", "kor": "연기"},
            {"yomigana": "えんちょう", "tango": "延長", "kor": "연장"},
            {"yomigana": "のびる", "tango": "延びる", "kor": "연장되다"},
            {"yomigana": "のばす", "tango": "延ばす", "kor": "연장시키다"},
            {"yomigana": "えんがん", "tango": "沿岸", "kor": "연안"},
            {"yomigana": "そう", "tango": "沿う", "kor": "따르다"},
            {"yomigana": "しゅうきょう", "tango": "宗教", "kor": "종교"},
            {"yomigana": "うちゅう", "tango": "宇宙", "kor": "우주"},
            {"yomigana": "ちゅうじつ", "tango": "忠実", "kor": "충실"},
        ]
    },
    "0721": {
        "label": "7월 21일",
        "pages": "109, 110",
        "words": [
            {"yomigana": "かくだい", "tango": "拡大", "kor": "확대"},
            {"yomigana": "かくちょう", "tango": "拡張", "kor": "확장"},
            {"yomigana": "こきゅう", "tango": "呼吸", "kor": "호흡"},
            {"yomigana": "よぶ", "tango": "呼ぶ", "kor": "부르다"},
            {"yomigana": "よびだし", "tango": "呼び出し", "kor": "호출"},
            {"yomigana": "かんごふ", "tango": "看護婦", "kor": "간호사"},
            {"yomigana": "かんびょう", "tango": "看病", "kor": "간병"},
            {"yomigana": "かんとう", "tango": "巻頭", "kor": "권두"},
            {"yomigana": "まき", "tango": "巻き", "kor": "말이"},
            {"yomigana": "まく", "tango": "巻く", "kor": "말다"},
            {"yomigana": "かいだん", "tango": "階段", "kor": "계단"},
            {"yomigana": "だんらく", "tango": "段落", "kor": "단락"},
            {"yomigana": "はいけい", "tango": "背景", "kor": "배경"},
            {"yomigana": "せ/せい", "tango": "背", "kor": "키"},
            {"yomigana": "せなか", "tango": "背中", "kor": "등"},
            {"yomigana": "きりつ", "tango": "規律", "kor": "규율"},
            {"yomigana": "ほうりつ", "tango": "法律", "kor": "법률"},
            {"yomigana": "さきん", "tango": "砂金", "kor": "사금"},
            {"yomigana": "どしゃ", "tango": "土砂", "kor": "토사"},
            {"yomigana": "すな", "tango": "砂", "kor": "모래"},
            {"yomigana": "どしゃぶり", "tango": "土砂降り", "kor": "억수"},
            {"yomigana": "せんげん", "tango": "宣言", "kor": "선언"},
            {"yomigana": "せんでん", "tango": "宣伝", "kor": "선전"},
            {"yomigana": "じょうない", "tango": "城内", "kor": "성내"},
            {"yomigana": "しろ", "tango": "城", "kor": "성"},
            {"yomigana": "せんたく", "tango": "洗濯", "kor": "세탁"},
            {"yomigana": "あらう", "tango": "洗う", "kor": "씻다"},
            {"yomigana": "おせん", "tango": "汚染", "kor": "오염"},
            {"yomigana": "かんせん", "tango": "感染", "kor": "감염"},
            {"yomigana": "でんせん", "tango": "伝染", "kor": "전염"},
            {"yomigana": "そまる", "tango": "染まる", "kor": "물들다"},
            {"yomigana": "そめる", "tango": "染める", "kor": "물들이다"},
            {"yomigana": "しみる", "tango": "染みる", "kor": "스며들다"},
            {"yomigana": "えいが", "tango": "映画", "kor": "영화"},
            {"yomigana": "じょうえい", "tango": "上映", "kor": "상영"},
            {"yomigana": "うつる", "tango": "映る", "kor": "비치다"},
            {"yomigana": "うつす", "tango": "映す", "kor": "비추다"},
            {"yomigana": "しせい", "tango": "姿勢", "kor": "자세"},
            {"yomigana": "すがた", "tango": "姿", "kor": "모습"},
            {"yomigana": "せんぎょう", "tango": "専業", "kor": "전업"},
            {"yomigana": "せんこう", "tango": "専攻", "kor": "전공"},
            {"yomigana": "せんもん", "tango": "専門", "kor": "전문"},
            {"yomigana": "えんそう", "tango": "演奏", "kor": "연주"},
        ]
    },
    "0722": {
        "label": "7월 22일",
        "pages": "111, 112",
        "words": [
            {"yomigana": "おんせん", "tango": "温泉", "kor": "온천"},
            {"yomigana": "いずみ", "tango": "泉", "kor": "샘"},
            {"yomigana": "はけん", "tango": "派遣", "kor": "파견"},
            {"yomigana": "はへい", "tango": "派兵", "kor": "파병"},
            {"yomigana": "はいえん", "tango": "肺炎", "kor": "폐렴"},
            {"yomigana": "かいかく", "tango": "改革", "kor": "개혁"},
            {"yomigana": "かくしん", "tango": "革新", "kor": "혁신"},
            {"yomigana": "かわ", "tango": "革", "kor": "가죽"},
            {"yomigana": "こうちゃ", "tango": "紅茶", "kor": "홍차"},
            {"yomigana": "こうよう", "tango": "紅葉", "kor": "단풍"},
            {"yomigana": "くちべに", "tango": "口紅", "kor": "입술연지"},
            {"yomigana": "こうしつ", "tango": "皇室", "kor": "황실"},
            {"yomigana": "こうてい", "tango": "皇帝", "kor": "황제"},
            {"yomigana": "こうすいりょう", "tango": "降水量", "kor": "강수량"},
            {"yomigana": "こうふく", "tango": "降伏", "kor": "항복"},
            {"yomigana": "ふる", "tango": "降る", "kor": "내리다(自)"},
            {"yomigana": "おりる", "tango": "降りる", "kor": "내리다(自)"},
            {"yomigana": "おろす", "tango": "降ろす", "kor": "내리다(他)"},
            {"yomigana": "のうこつ", "tango": "納骨", "kor": "납골"},
            {"yomigana": "こっかく", "tango": "骨格", "kor": "골격"},
            {"yomigana": "ほね", "tango": "骨", "kor": "뼈"},
            {"yomigana": "のうにゅう", "tango": "納入", "kor": "납입"},
            {"yomigana": "なっとく", "tango": "納得", "kor": "납득"},
            {"yomigana": "すいとう", "tango": "出納", "kor": "출납"},
            {"yomigana": "おさまる", "tango": "納まる", "kor": "걷히다"},
            {"yomigana": "おさめる", "tango": "納める", "kor": "걷다"},
            {"yomigana": "せいとう", "tango": "政党", "kor": "정당"},
            {"yomigana": "やとう", "tango": "野党", "kor": "야당"},
            {"yomigana": "よとう", "tango": "与党", "kor": "여당"},
            {"yomigana": "めいろう", "tango": "明朗", "kor": "명랑"},
            {"yomigana": "ろうどく", "tango": "朗読", "kor": "낭독"},
            {"yomigana": "はんちょう", "tango": "班長", "kor": "반장"},
            {"yomigana": "はいゆう", "tango": "俳優", "kor": "배우"},
            {"yomigana": "はいく", "tango": "俳句", "kor": "하이쿠"},
            {"yomigana": "ひけつ", "tango": "秘訣", "kor": "비결"},
            {"yomigana": "ひみつ", "tango": "秘密", "kor": "비밀"},
            {"yomigana": "しゃさつ", "tango": "射殺", "kor": "사살"},
            {"yomigana": "はっしゃ", "tango": "発射", "kor": "발사"},
            {"yomigana": "たんじゅん", "tango": "単純", "kor": "단순"},
            {"yomigana": "じゅんすい", "tango": "純粋", "kor": "순수"},
        ]
    },
    "0723": {
        "label": "7월 23일",
        "pages": "113, 114",
        "words": [
            {"yomigana": "さんぎょう", "tango": "蚕業", "kor": "양잠업"},
            {"yomigana": "かいこ", "tango": "蚕", "kor": "누에"},
            {"yomigana": "しょうぐん", "tango": "将軍", "kor": "장군"},
            {"yomigana": "しょうぎ", "tango": "将棋", "kor": "장기"},
            {"yomigana": "てんかい", "tango": "展開", "kor": "전개"},
            {"yomigana": "てんらんかい", "tango": "展覧会", "kor": "전람회"},
            {"yomigana": "てんぼう", "tango": "展望", "kor": "전망"},
            {"yomigana": "はってん", "tango": "発展", "kor": "발전"},
            {"yomigana": "かいじょ", "tango": "解除", "kor": "해제"},
            {"yomigana": "じょめい", "tango": "除名", "kor": "제명"},
            {"yomigana": "そうじ", "tango": "掃除", "kor": "청소"},
            {"yomigana": "のぞく", "tango": "除く", "kor": "제거하다"},
            {"yomigana": "じゅうぎょういん", "tango": "従業員", "kor": "종업원"},
            {"yomigana": "ふくじゅう", "tango": "服従", "kor": "복종"},
            {"yomigana": "したがえる", "tango": "従える", "kor": "따르게하다"},
            {"yomigana": "したがう", "tango": "従う", "kor": "따르다"},
            {"yomigana": "ざせき", "tango": "座席", "kor": "좌석"},
            {"yomigana": "ざだんかい", "tango": "座談会", "kor": "좌담회"},
            {"yomigana": "すわる", "tango": "座る", "kor": "앉다"},
            {"yomigana": "かぶしき", "tango": "株式", "kor": "주식"},
            {"yomigana": "かち", "tango": "価値", "kor": "가치"},
            {"yomigana": "ねだん", "tango": "値段", "kor": "가격"},
            {"yomigana": "あたい", "tango": "値", "kor": "가격"},
            {"yomigana": "ほうしん", "tango": "方針", "kor": "방침"},
            {"yomigana": "はり", "tango": "針", "kor": "바늘"},
            {"yomigana": "へいか", "tango": "陛下", "kor": "폐하"},
            {"yomigana": "けんとう", "tango": "検討", "kor": "검토"},
            {"yomigana": "とうろん", "tango": "討論", "kor": "토론"},
            {"yomigana": "きょうい", "tango": "胸囲", "kor": "흉위"},
            {"yomigana": "どきょう", "tango": "度胸", "kor": "배짱/담력"},
            {"yomigana": "むね", "tango": "胸", "kor": "가슴"},
            {"yomigana": "むなさわぎ", "tango": "胸騒ぎ", "kor": "설렘"},
            {"yomigana": "ずのう", "tango": "頭脳", "kor": "두뇌"},
            {"yomigana": "みつりん", "tango": "密林", "kor": "밀림"},
            {"yomigana": "みっしつ", "tango": "密室", "kor": "밀실"},
            {"yomigana": "みっちゃく", "tango": "密着", "kor": "밀착"},
            {"yomigana": "ひそかだ", "tango": "密かだ", "kor": "은밀하다"},
            {"yomigana": "ほうもん", "tango": "訪問", "kor": "방문"},
            {"yomigana": "おとずれる", "tango": "訪れる", "kor": "방문하다"},
            {"yomigana": "たずねる", "tango": "訪ねる", "kor": "방문하다"},
            {"yomigana": "よくじつ", "tango": "翌日", "kor": "익일"},
        ]
    },
    "0728": {
        "label": "7월 28일",
        "pages": "115, 116",
        "words": [
            {"yomigana": "ちょしゃ", "tango": "著者", "kor": "저자"},
            {"yomigana": "いちじるしい", "tango": "著しい", "kor": "두드러지다"},
            {"yomigana": "ちょうじょう", "tango": "頂上", "kor": "정상"},
            {"yomigana": "いただく", "tango": "頂く", "kor": "받들다"},
            {"yomigana": "へんさい", "tango": "返済", "kor": "변제"},
            {"yomigana": "すむ", "tango": "済む", "kor": "끝나다"},
            {"yomigana": "すます", "tango": "済ます", "kor": "끝내다"},
            {"yomigana": "たんきゅう", "tango": "探求", "kor": "탐구"},
            {"yomigana": "たんけん", "tango": "探検", "kor": "탐험"},
            {"yomigana": "さがす", "tango": "探す", "kor": "찾다"},
            {"yomigana": "どうそう", "tango": "同窓", "kor": "동창"},
            {"yomigana": "まどぐち", "tango": "窓口", "kor": "창구"},
            {"yomigana": "すいせん", "tango": "推薦", "kor": "추천"},
            {"yomigana": "すいそく", "tango": "推測", "kor": "추측"},
            {"yomigana": "へいさ", "tango": "閉鎖", "kor": "폐쇄"},
            {"yomigana": "みっぺい", "tango": "密閉", "kor": "밀폐"},
            {"yomigana": "とじる", "tango": "閉じる", "kor": "닫다/닫히다"},
            {"yomigana": "しまる", "tango": "閉まる", "kor": "닫히다"},
            {"yomigana": "しめる", "tango": "閉める", "kor": "닫다"},
            {"yomigana": "ききょう", "tango": "帰郷", "kor": "귀향"},
            {"yomigana": "きか", "tango": "貴下", "kor": "귀하"},
            {"yomigana": "きちょう", "tango": "貴重", "kor": "귀중"},
            {"yomigana": "とうとい/たっとい", "tango": "貴い", "kor": "소중하다"},
            {"yomigana": "けいろう", "tango": "敬老", "kor": "경로"},
            {"yomigana": "そんけい", "tango": "尊敬", "kor": "존경"},
            {"yomigana": "きんむ", "tango": "勤務", "kor": "근무"},
            {"yomigana": "しゅっきん", "tango": "出勤", "kor": "출근"},
            {"yomigana": "つうきん", "tango": "通勤", "kor": "통근"},
            {"yomigana": "つとめる", "tango": "勤める", "kor": "근무하다"},
            {"yomigana": "きんにく", "tango": "筋肉", "kor": "근육"},
            {"yomigana": "すじ", "tango": "筋", "kor": "줄기"},
            {"yomigana": "こんばん", "tango": "今晩", "kor": "오늘 밤"},
            {"yomigana": "まいばん", "tango": "毎晩", "kor": "매일 밤"},
            {"yomigana": "こうほ", "tango": "候補", "kor": "후보"},
            {"yomigana": "ほじゅう", "tango": "補充", "kor": "보충"},
            {"yomigana": "ほじょ", "tango": "補助", "kor": "보조"},
            {"yomigana": "おぎなう", "tango": "補う", "kor": "보충하다"},
            {"yomigana": "しゅしゃ", "tango": "取捨", "kor": "취사"},
            {"yomigana": "すてる", "tango": "捨てる", "kor": "버리다"},
            {"yomigana": "せいきょう", "tango": "盛況", "kor": "성황"},
            {"yomigana": "はんじょう", "tango": "繁盛", "kor": "번성"},
            {"yomigana": "もる", "tango": "盛る", "kor": "쌓다담다"},
            {"yomigana": "さかんだ", "tango": "盛んだ", "kor": "번성하다"},
        ]
    },
    "0729": {
        "label": "7월 29일",
        "pages": "117, 118",
        "words": [
            {"yomigana": "えんし", "tango": "遠視", "kor": "원시"},
            {"yomigana": "きんし", "tango": "近視", "kor": "근시"},
            {"yomigana": "しりょく", "tango": "視力", "kor": "시력"},
            {"yomigana": "くいき", "tango": "区域", "kor": "구역"},
            {"yomigana": "ちいき", "tango": "地域", "kor": "지역"},
            {"yomigana": "つうやく", "tango": "通訳", "kor": "통역"},
            {"yomigana": "ほんやく", "tango": "翻訳", "kor": "번역"},
            {"yomigana": "わけ", "tango": "訳", "kor": "이유"},
            {"yomigana": "いよく", "tango": "意欲", "kor": "의욕"},
            {"yomigana": "しょくよく", "tango": "食欲", "kor": "식욕"},
            {"yomigana": "よくぼう", "tango": "欲望", "kor": "욕망"},
            {"yomigana": "ほしい", "tango": "欲しい", "kor": "바라다"},
            {"yomigana": "ゆうびんきょく", "tango": "郵便局", "kor": "우체국"},
            {"yomigana": "ゆうそう", "tango": "郵送", "kor": "우송"},
            {"yomigana": "いこく", "tango": "異国", "kor": "이국"},
            {"yomigana": "いせい", "tango": "異性", "kor": "이성"},
            {"yomigana": "ことなる", "tango": "異なる", "kor": "다르다"},
            {"yomigana": "しゅうしょく", "tango": "就職", "kor": "취직"},
            {"yomigana": "つく", "tango": "就く", "kor": "취임하다/들다"},
            {"yomigana": "いつう", "tango": "胃痛", "kor": "위통"},
            {"yomigana": "くつう", "tango": "苦痛", "kor": "고통"},
            {"yomigana": "ずつう", "tango": "頭痛", "kor": "두통"},
            {"yomigana": "いたむ", "tango": "痛む", "kor": "아프다"},
            {"yomigana": "いためる", "tango": "痛める", "kor": "아프게하다"},
            {"yomigana": "けいようし", "tango": "形容詞", "kor": "형용사"},
            {"yomigana": "どうし", "tango": "動詞", "kor": "동사"},
            {"yomigana": "めいし", "tango": "名詞", "kor": "명사"},
            {"yomigana": "かいぜん", "tango": "改善", "kor": "개선"},
            {"yomigana": "ぎぜん", "tango": "偽善", "kor": "위선"},
            {"yomigana": "よい", "tango": "善い", "kor": "좋다"},
            {"yomigana": "そうち", "tango": "装置", "kor": "장치"},
            {"yomigana": "そうび", "tango": "装備", "kor": "장비"},
            {"yomigana": "いしょう", "tango": "衣装", "kor": "의상"},
            {"yomigana": "けっさい", "tango": "決裁", "kor": "결재"},
            {"yomigana": "さいばんしょ", "tango": "裁判所", "kor": "재판소"},
            {"yomigana": "さばく", "tango": "裁く", "kor": "심판하다"},
            {"yomigana": "そんけい", "tango": "尊敬", "kor": "존경"},
            {"yomigana": "そんちょう", "tango": "尊重", "kor": "존중"},
            {"yomigana": "とうとい/たっとい", "tango": "尊い", "kor": "소중하다"},
            {"yomigana": "こうしゅう", "tango": "公衆", "kor": "공중"},
            {"yomigana": "たいしゅう", "tango": "大衆", "kor": "대중"},
            {"yomigana": "そうかん", "tango": "創刊", "kor": "창간"},
            {"yomigana": "そうりつ", "tango": "創立", "kor": "창립"},
            {"yomigana": "どくそう", "tango": "独創", "kor": "독창"},
            {"yomigana": "せいさく", "tango": "政策", "kor": "정책"},
            {"yomigana": "たいさく", "tango": "対策", "kor": "대책"},
        ]
    },
}
